FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

COPY app/ app/
COPY tasks/ tasks/
COPY models/ models/

CMD ["celery", "-A", "tasks.celery_app.celery_app", "worker", "--loglevel=info"]
