# Builder stage
FROM python:3.10-slim as builder

WORKDIR /install

COPY requirements.txt .

RUN pip install --prefix=/install -r requirements.txt


# Runtime stage
FROM python:3.10-slim

WORKDIR /app

COPY --from=builder /install /usr/local

COPY tasks ./tasks
COPY models ./models
COPY app ./app

ENV PYTHONUNBUFFERED=1

CMD ["celery", "-A", "tasks.celery_app", "worker", "--loglevel=info"]